name: Publish Image
on:
  push:
    tags:
      - 'v*'
jobs:
  test-and-build:
    uses: ./.github/workflows/tests.yml
  publish-container:
    runs-on: ubuntu-latest
    steps:
      - name: lowercase github.repository
        run: echo "IMAGE_NAME=${GITHUB_REPOSITORY@L}" >> ${GITHUB_ENV}
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image with playground
        uses: docker/build-push-action@v5
        with:
          context: ./
          tags: |
            ${{ vars.DOCKERHUB_REPOSITORY }}:latest
            ${{ vars.DOCKERHUB_REPOSITORY }}:${{ github.ref_name }}
            ghcr.io/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          push: true

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_REPOSITORY: ${{ vars.DOCKERHUB_REPOSITORY}}
          short-description: ${{ github.event.repository.description }}
