name: Publish Image
on:
  push:
    tags:
      - 'v*'
jobs:
  test-and-build:
    uses: ./.github/workflows/tests.yml
  publish-container:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image with playground
        uses: docker/build-push-action@v5
        with:
          context: ./
          tags: |
            ${{ env.DOCKERHUB_REPOSITORY}}:latest
            ${{ env.DOCKERHUB_REPOSITORY}}:${{ github.ref.name }}
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.ref.name }}
          push: true

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_REPOSITORY: ${{ env.DOCKERHUB_REPOSITORY}}
          short-description: ${{ github.event.repository.description }}
