name: build and test
on:
  push:
    paths-ignore:
      - '**/README.md'
      - '**/README_DEV.md'
      - '.vscode/**'
      - '.dockerignore'
      - '.gitignore'

jobs:
  test-and-build:
    uses: ./.github/workflows/tests.yml
